### ISSUE TITLE
[init] 솝커톤 프로젝트 초기 세팅

### ISSUE THREAD

**Issue by hwangsunwoong** [DO-SOPT-SOPKATHON-Web-1/server#1]
## Issue 📌
솝커톤 프로젝트 초기 세팅

## Todo ✔️
- [x] issue 템플릿 추가
- [x] pull request 템플릿 추가
- [x] .gitignore 설정
- [x] 인프라 아키텍처 설계
- [x] 도메인 발급
- [x] SSL 인증서 발급
- [x] EC2 세팅
- [x] RDS 세팅
- [x] Nginx 세팅
- [x] CI/CD 세팅
- [x] 프로젝트 초기 세팅
- [x] README 초안 작성
